name: Daily Countdown Video Upload

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 10 AM Washington time
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Debug Step: Check if GitHub Actions Receives the Secret
      - name: Debug Google Drive Secret
        run: |
          echo "Secret Length: ${#secrets.GOOGLE_DRIVE_CREDENTIALS}"


      - name: Configure Google Drive Credentials
        run: |
          echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > credentials.json

      - name: Generate and Upload Video
        run: python generate_daily_video.py
