name: Daily Countdown Video Upload

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 10 AM Washington time
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Debug Step: Check if GitHub is passing `GOOGLE_DRIVE_CREDENTIALS`
      - name: Check Environment Variables
        run: printenv | grep GOOGLE

      - name: Configure Google Drive Credentials
        run: |
          if [ -z "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" ]; then
            echo "🚨 GOOGLE_DRIVE_CREDENTIALS is missing!"
            exit 1
          else
            echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > credentials.json
            echo "✅ GOOGLE_DRIVE_CREDENTIALS has been saved!"
          fi

      - name: Generate and Upload Video
        run: python generate_daily_video.py
